version: '3.8'
services:
  routine_service:
    container_name: routines_service
    build: .
    ports:
      - '3001:3001'
    networks:
      - shared_network

networks:
  shared_network:
    external: true